spring:
  application:
    name: batch-app
  
  datasource:
    url: jdbc:h2:mem:batchdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  
  batch:
    job:
      enabled: false

server:
  port: 8081

logging:
  level:
    com.example: DEBUG